# Generated by Django 5.0.4 on 2024-09-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0003_rename_japeword_japaword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eng_Word',
            new_name='EngWord',
        ),
    ]
