# Generated by Django 5.0.4 on 2024-10-21 02:10

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engword',
            name='antonyms',
            field=models.ManyToManyField(blank=True, null=True, to='word_learning.engword'),
        ),
        migrations.AlterField(
            model_name='engword',
            name='meaning',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='engword',
            name='part_of_speech',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection'), ('article', 'Article')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='engword',
            name='synonyms',
            field=models.ManyToManyField(blank=True, null=True, to='word_learning.engword'),
        ),
    ]
