# Generated by Django 5.0.4 on 2024-09-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='JapeWord',
        ),
    ]
