# Generated by Django 5.0.4 on 2024-09-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0002_rename_choice_japeword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JapeWord',
            new_name='JapaWord',
        ),
    ]
