# Generated by Django 5.0.4 on 2024-10-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0002_alter_engword_antonyms_alter_engword_meaning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engword',
            name='cefr',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
