# Generated by Django 5.0.4 on 2024-10-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0003_engword_cefr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engword',
            name='eng_word',
            field=models.CharField(max_length=30),
        ),
    ]
