# Generated by Django 5.0.4 on 2024-09-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0004_rename_eng_word_engword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='japaword',
            name='eng_mean',
        ),
        migrations.AddField(
            model_name='engword',
            name='meaning',
            field=models.ManyToManyField(to='word_learning.japaword'),
        ),
        migrations.AlterField(
            model_name='engword',
            name='eng_word',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='japaword',
            name='japa_word',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
