# Generated by Django 5.0.4 on 2024-09-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0005_remove_japaword_eng_mean_engword_meaning_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engword',
            name='meaning',
        ),
        migrations.DeleteModel(
            name='JapaWord',
        ),
        migrations.AddField(
            model_name='engword',
            name='meaning',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
