# Generated by Django 5.0.4 on 2024-10-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0006_rename_recomend_engword_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engword',
            name='cefr',
            field=models.CharField(blank=True, choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Mastery')], max_length=2, null=True),
        ),
    ]
