# Generated by Django 5.0.4 on 2024-09-20 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0006_remove_engword_meaning_delete_japaword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=60)),
                ('eng_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_learning.engword')),
            ],
        ),
    ]
