# Generated by Django 5.0.4 on 2024-09-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0007_examplesentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='engword',
            name='antonyms',
            field=models.ManyToManyField(blank=True, to='word_learning.engword'),
        ),
        migrations.AddField(
            model_name='engword',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='engword',
            name='synonyms',
            field=models.ManyToManyField(blank=True, to='word_learning.engword'),
        ),
    ]
