# Generated by Django 5.0.4 on 2024-09-20 07:35

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0009_alter_engword_part_of_speech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engword',
            name='part_of_speech',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection'), ('article', 'Article')], max_length=30),
        ),
    ]
