# Generated by Django 5.0.4 on 2024-09-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0010_alter_engword_part_of_speech'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrittingQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.CharField(max_length=1000)),
            ],
        ),
    ]
