# Generated by Django 5.0.4 on 2024-09-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0011_writtingquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='writtingquiz',
            name='llm_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
