# Generated by Django 5.0.4 on 2024-09-28 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0013_writtingquiz_created_at_writtingquiz_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrittingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_learning.writtingquiz')),
            ],
        ),
    ]
