# Generated by Django 5.0.4 on 2024-09-29 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0014_writtinganswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writtingquiz',
            name='score',
        ),
        migrations.AddField(
            model_name='writtinganswer',
            name='score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='writtinganswer',
            name='scored',
            field=models.BooleanField(default=False),
        ),
    ]
