# Generated by Django 5.0.4 on 2024-09-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0015_remove_writtingquiz_score_writtinganswer_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writtinganswer',
            name='comment',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
