# Generated by Django 5.0.4 on 2024-10-04 01:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0016_writtinganswer_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writtinganswer',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
